In [1]:
import warnings
warnings.filterwarnings("ignore")
import sys, os
sys.path.append(os.path.abspath("../.."))
from configs import GOOGLE_APPLICATION_CREDENTIALS,GCS_BUCKET_NAME,GCS_PROJECT_ID
from google.cloud import bigquery
from src.utils.io_utils import upload_to_bigquery,upload_to_db
from clean_utils import *

In [2]:
client = bigquery.Client.from_service_account_json(GOOGLE_APPLICATION_CREDENTIALS)
table_name ="data_merged"
table_id = f"{GCS_PROJECT_ID}.{GCS_BUCKET_NAME}.{table_name}"

In [3]:
query = """SELECT *
FROM `khangtestdbt.xecupredict.oto_com` """
data_oto = client.query(query).to_dataframe()
data_oto.head(1)

,Name,Price,Năm_SX,Nhiên_liệu,Kiểu_dáng,Tình_trạng,Km_đã_đi,Hộp_số,Xuất_xứ,Tỉnh_thành,Số_tiền_vay,Thời_gian_vay,Lãi_xuất,Loại_hình,Giá_trị_xe_muốn_mua
0,Suzuki Grand vitara 2.0 AT 2003,155 triệu,2003,Máy xăng,SUV,Xe cũ,128.000 km,Số tự động,Nhập khẩu,Bắc Từ Liêm - Hà Nội,VNĐ,ThángNăm,ThángNăm,"Trả góp đều hàng thángTrả góp đều, lãi tính tr...",VNĐ

In [4]:
df_oto = data_oto.copy()

In [5]:
df_oto.columns

Index(['Name', 'Price', 'Năm_SX', 'Nhiên_liệu', 'Kiểu_dáng', 'Tình_trạng',
       'Km_đã_đi', 'Hộp_số', 'Xuất_xứ', 'Tỉnh_thành', 'Số_tiền_vay',
       'Thời_gian_vay', 'Lãi_xuất', 'Loại_hình', 'Giá_trị_xe_muốn_mua'],
      dtype='object')

In [6]:
df_oto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2041 entries, 0 to 2040
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 2039 non-null   object
 1   Price                2039 non-null   object
 2   Năm_SX               2039 non-null   object
 3   Nhiên_liệu           2039 non-null   object
 4   Kiểu_dáng            1796 non-null   object
 5   Tình_trạng           2039 non-null   object
 6   Km_đã_đi             2006 non-null   object
 7   Hộp_số               2036 non-null   object
 8   Xuất_xứ              2006 non-null   object
 9   Tỉnh_thành           2039 non-null   object
 10  Số_tiền_vay          2039 non-null   object
 11  Thời_gian_vay        2039 non-null   object
 12  Lãi_xuất             2039 non-null   object
 13  Loại_hình            2039 non-null   object
 14  Giá_trị_xe_muốn_mua  2039 non-null   object
dtypes: object(15)
memory usage: 239.3+ KB

In [7]:
df_oto = df_oto.rename(columns={
    "Nhiên_liệu": "fuel",
    "Kiểu_dáng": "body",
    "Km_đã_đi": "km",
    "Xuất_xứ": "origin",
    "Name": "name",
    "Price": "price",
    "Năm_SX": "year",
    "Hộp_số": "gearbox",
    "Tình_trạng": "status",
})

In [8]:
df_oto = df_oto[['fuel', 'body', 'km', 'origin', 'name','price', 'year','status', 'gearbox']]

1.name

In [9]:
df_oto.head()

,fuel,body,km,origin,name,price,year,status,gearbox
0,Máy xăng,SUV,128.000 km,Nhập khẩu,Suzuki Grand vitara 2.0 AT 2003,155 triệu,2003,Xe cũ,Số tự động
1,Máy xăng,SUV,128.000 km,Nhập khẩu,Suzuki Grand vitara 2.0 AT 2003,155 triệu,2003,Xe cũ,Số tự động
2,Máy xăng,Sedan,280.000 km,Nhập khẩu,Toyota Camry 2.4G 2005,180 triệu,2005,Xe cũ,Số sàn
3,Máy xăng,Sedan,86.000 km,Nhập khẩu,Toyota Camry 2005,200 triệu,2005,Xe cũ,Số sàn
4,Máy xăng,Sedan,130.000 km,Nhập khẩu,Rolls-Royce Ghost Series II 2010,3 tỉ 990 triệu,2010,Xe cũ,Số tự động

2.price

In [10]:
df_oto["price"].isna().sum()

np.int64(2)

In [11]:
def clean_price(x):
    if pd.isna(x):
        return None
    
    x = str(x).lower().strip()

    if x in ["", "none", "nan", "giá liên hệ", "contact", "-"]:
        return None

    x = x.replace("triệu", "triệu").replace("trieuj", "triệu")
    x = x.replace("ty", "tỷ").replace("ti", "tỷ")

    x = x.replace("tỉ", "tỷ")

    x = re.sub(r"\s+", " ", x)

    if "triệu" not in x and "tỷ" not in x:
        digits = re.sub(r"[^\d]", "", x)
        return int(digits) if digits.isdigit() else None

    x = x.replace(",", ".")  

    match = re.match(r"(\d*\.?\d*)\s*tỷ\s*(\d*\.?\d*)?\s*triệu?", x)
    if match:
        ty = float(match.group(1)) if match.group(1) else 0
        trieu = float(match.group(2)) if match.group(2) else 0
        return int(ty * 1_000_000_000 + trieu * 1_000_000)

    if "tỷ" in x:
        num = re.findall(r"[\d\.]+", x)
        if num:
            return int(float(num[0]) * 1_000_000_000)
        return None

    if "triệu" in x:
        num = re.findall(r"[\d\.]+", x)
        if num:
            return int(float(num[0]) * 1_000_000)
        return None

    return None

In [12]:
df_oto["price"] = df_oto["price"].apply(clean_price)
df_oto.sample(5)

,fuel,body,km,origin,name,price,year,status,gearbox
1264,Máy xăng,Crossover,35.000 km,Trong nước,Toyota Corolla Cross 1.8 V 2021,675000000.0,2021,Xe cũ,Số tự động
1507,Máy xăng,SUV,65.000 km,Nhập khẩu,Kia Sportage 2022,820000000.0,2022,Xe cũ,Số tự động
1251,Máy xăng,None,86.000 km,Trong nước,Toyota Corolla Altis 2019,529000000.0,2019,Xe cũ,Số tự động
1053,Máy xăng,None,55.000 km,Nhập khẩu,Hyundai Accent 2022,450000000.0,2022,Xe cũ,Số tự động
734,Máy xăng,Hatchback,34.000 km,Nhập khẩu,Toyota Wigo 2024,368000000.0,2024,Xe cũ,Số tự động

In [13]:
df_oto["price"].isna().sum()

np.int64(2)

In [14]:
df_oto = df_oto[df_oto["price"] > 50000000]

3.brand

In [15]:
df_oto["brand"] = df_oto["name"].str.strip().str.split().str[0]

In [16]:
df_oto["brand"].isna().sum()

np.int64(0)

In [17]:
df_oto["brand"] = df_oto["brand"].str.lower()

4.year

In [18]:
df_oto["year"].head(5)

0    2003
1    2003
2    2005
3    2005
4    2010
Name: year, dtype: object

In [19]:
df_oto["year"].isna().sum()

np.int64(0)

In [20]:
df_oto["age"] = 2026 - df_oto["year"].astype(int)
df_oto.drop(columns=["year"], inplace=True)
df_oto.head(1)

,fuel,body,km,origin,name,price,status,gearbox,brand,age
0,Máy xăng,SUV,128.000 km,Nhập khẩu,Suzuki Grand vitara 2.0 AT 2003,155000000.0,Xe cũ,Số tự động,suzuki,23

5.status

In [21]:
df_oto["status"].unique()

array(['Xe cũ'], dtype=object)

In [22]:
df_oto.drop(columns=["status"], inplace=True)

6.km

In [23]:
df_oto["km"].head(5)

0    128.000 km
1    128.000 km
2    280.000 km
3     86.000 km
4    130.000 km
Name: km, dtype: object

In [24]:
df_oto["km"].isna().sum()

np.int64(33)

In [25]:
import numpy as np
def cv_km(x):
    if pd.isna(x):
        return np.nan
    
    if isinstance(x, (int, float)):
        return x
    
    x = str(x).lower().strip()

    if x in ["", "-", "none", "nan"]:
        return np.nan

    # giữ lại số
    digits = re.sub(r"[^\d]", "", x)

    return int(digits) if digits else np.nan

In [26]:
df_oto["km"] = df_oto["km"].apply(cv_km)

In [27]:
df_oto = df_oto[
    (df_oto["km"] > 50) | (df_oto["km"].isna())
]

In [28]:
df_oto["km"].isna().sum()

np.int64(33)

7.origin

In [29]:
df_oto["origin"].isna().sum()

np.int64(33)

In [30]:
df_oto["origin"].value_counts()

origin
Nhập khẩu     1137
Trong nước     844
Name: count, dtype: int64

In [31]:
df_oto["origin"] = df_oto["origin"].replace({
    "Trong nước": "trong nước",
    "Nhập khẩu": "nhập khẩu"
})

In [32]:
df_oto["origin"].isna().sum()

np.int64(33)

8.body

In [33]:
df_oto["body"].unique()

array(['SUV', 'Sedan', 'Van/Minivan', 'Hatchback', None, 'MPV',
       'Crossover', 'Sport Car', 'Coupe', 'Bán tải', 'Convertible',
       'Minibus', 'Xe tải'], dtype=object)

In [34]:
df_oto["body"] = df_oto["body"].str.lower().str.strip()

In [35]:
df_oto["body"].isna().sum()

np.int64(242)

9.fuel

In [36]:
df_oto["fuel"].unique()

array(['Máy xăng', 'Máy dầu', 'Hybrid', 'Điện'], dtype=object)

In [37]:
df_oto["fuel"] = df_oto["fuel"].apply(clean_fuel)

In [38]:
df_oto["fuel"].unique()

array(['Xăng', 'Dầu', 'Hybrid', 'Điện'], dtype=object)

In [39]:
df_oto["fuel"].isna().sum()

np.int64(0)

10.gearbox

In [40]:
df_oto["gearbox"].isna().sum()

np.int64(3)

In [41]:
df_oto["gearbox"].unique()

array(['Số tự động', 'Số sàn', None], dtype=object)

11.updata

In [42]:
upload_to_bigquery(df_oto, table_id=table_id, if_exists="append" )

✅ Uploaded 2014 rows to khangtestdbt.xecupredict.data_merged

In [43]:
upload_to_db(df_oto,table_name)

✅ Saved 2014 rows to PostgreSQL table 'data_merged'

In [44]:
# end