In [1]:
import warnings
warnings.filterwarnings("ignore")
import sys, os
sys.path.append(os.path.abspath("../.."))
from configs import GOOGLE_APPLICATION_CREDENTIALS,GCS_BUCKET_NAME,GCS_PROJECT_ID
from google.cloud import bigquery
from src.utils.io_utils import upload_to_bigquery

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import r2_score, mean_squared_error, root_mean_squared_error, mean_absolute_error
import pandas as pd
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.tree import DecisionTreeRegressor

In [3]:
client = bigquery.Client.from_service_account_json(GOOGLE_APPLICATION_CREDENTIALS)

In [4]:
query = """SELECT *
FROM `khangtestdbt.xecupredict.data_train_model` """
data = client.query(query).to_dataframe()
data.head(1)

,km,age,km_per_year,log_age,origin_Nhập Khẩu,origin_Trong Nước,body_Convertible,body_Coupe,body_Hatchback,body_Kiểu Dáng Khác,...,is_imported_True,imported_age_False_Mid,imported_age_False_New,imported_age_False_Old,imported_age_False_Young,imported_age_True_Mid,imported_age_True_New,imported_age_True_Old,imported_age_True_Young,price
0,-1.348089,-1.086785,-1.789765,-1.490741,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,410000000.0

In [5]:
df = data.copy()

In [6]:
df.shape

(16796, 84)

In [7]:
X = df.drop(columns=["price"])
y = np.log(df["price"])

In [8]:
np.random.seed(42)

X_train, X_test, y_train, y_test =  train_test_split(X,
                                                     y,
                                                     test_size=0.2)

In [44]:
models = {
    "Linear Regression": LinearRegression(),
    "Ridge Regression": Ridge(),
    "Lasso Regression": Lasso(),
    "Decision Tree": DecisionTreeRegressor()
}

In [45]:
trained_models = {} 
rows = []

for name, model in models.items():
    model.fit(X_train, y_train)

    trained_models[name] = model

    train_pred = model.predict(X_train)
    test_pred  = model.predict(X_test)

    r2_train = r2_score(y_train, train_pred)
    r2_test  = r2_score(y_test, test_pred)

    mse_train = mean_squared_error(y_train, train_pred)
    mse_test  = mean_squared_error(y_test, test_pred)

    rmse_train = np.sqrt(mse_train)
    rmse_test  = np.sqrt(mse_test)

    mae_train = mean_absolute_error(y_train, train_pred)
    mae_test  = mean_absolute_error(y_test, test_pred)

    rows.append([
        name,
        r2_train, r2_test,
        rmse_train, rmse_test,
        mse_train, mse_test,
        mae_train, mae_test
    ])

df_results = pd.DataFrame(
    rows,
    columns=[
        "Model",
        "R2_Train", "R2_Test",
        "RMSE_Train", "RMSE_Test",
        "MSE_Train", "MSE_Test",
        "MAE_Train", "MAE_Test"
    ]
)

df_results

,Model,R2_Train,R2_Test,RMSE_Train,RMSE_Test,MSE_Train,MSE_Test,MAE_Train,MAE_Test
0,Linear Regression,0.786885,0.785004,3.890318e-01,0.389941,1.513458e-01,0.152054,2.716225e-01,0.272326
1,Ridge Regression,0.786867,0.784972,3.890480e-01,0.389969,1.513584e-01,0.152076,2.716984e-01,0.272471
2,Lasso Regression,0.000000,-0.000129,8.427102e-01,0.841029,7.101604e-01,0.707329,6.266321e-01,0.622213
3,Decision Tree,1.000000,0.785229,9.194888e-17,0.389736,8.454597e-33,0.151894,2.379758e-18,0.239383

In [19]:
round(np.exp(0.272471)-1,2)

np.float64(0.31)

In [20]:
round(np.exp(0.272471)-1,2)

np.float64(0.31)

In [21]:
round(np.exp(0.240867)-1,2)

np.float64(0.27)

In [33]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

dt_param_grid = {
    'max_depth': [3, 5, 7, 10],
    'min_samples_split': [5, 10, 20],
    'min_samples_leaf': [2, 5, 10, 20],
    'min_impurity_decrease': [0.0, 0.0001, 0.001]
}

dt_grid = GridSearchCV(
    DecisionTreeRegressor(random_state=42),
    param_grid=dt_param_grid,
    scoring='neg_mean_squared_error',
    cv=5,
    n_jobs=-1,
    verbose=1
)

dt_grid.fit(X_train, y_train)
dt_best = dt_grid.best_estimator_

y_tr_pred = dt_best.predict(X_train)
y_te_pred = dt_best.predict(X_test)

print("==== Decision Tree ====")
print("Best params:", dt_grid.best_params_)

Fitting 5 folds for each of 144 candidates, totalling 720 fits
==== Decision Tree ====
Best params: {'max_depth': 10, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 5, 'min_samples_split': 20}

In [34]:
print("==== Decision Tree ====")
print("Best params:", dt_grid.best_params_)

print("R2 Train:", r2_score(y_train, y_tr_pred))
print("R2 Test :", r2_score(y_test, y_te_pred))

print("RMSE Train:", np.sqrt(mean_squared_error(y_train, y_tr_pred)))
print("RMSE Test :", np.sqrt(mean_squared_error(y_test, y_te_pred)))

print("MSE Train:", mean_squared_error(y_train, y_tr_pred))
print("MSE Test :", mean_squared_error(y_test, y_te_pred))

print("MAE Train:", mean_absolute_error(y_train, y_tr_pred))
print("MAE Test :", mean_absolute_error(y_test, y_te_pred))

==== Decision Tree ====
Best params: {'max_depth': 10, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 5, 'min_samples_split': 20}
R2 Train: 0.8483072253832831
R2 Test : 0.8151738599311661
RMSE Train: 0.3282167057004997
RMSE Test : 0.3615468822291197
MSE Train: 0.10772620590088842
MSE Test : 0.13071614804959694
MAE Train: 0.2241413763025331
MAE Test : 0.2474014170608895

In [35]:
round(np.exp(0.22056547789827974)-1,2)

np.float64(0.25)

In [36]:
round(np.exp(0.24741024512313228)-1,2)

np.float64(0.28)

* save model

In [37]:
import joblib

joblib.dump(trained_models["Linear Regression"], "../../model/lr_best.joblib")
joblib.dump(trained_models["Ridge Regression"], "../../model/rr_best.joblib")

joblib.dump(dt_best, "../../model/dt_best.joblib")

['../../model/dt_best.joblib']

In [38]:
# end

In [39]:
importance = pd.Series(
    dt_best.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print(importance.head(20))

log_age                 0.362697
gearbox_Số tự động      0.130525
brand_group_Other       0.083621
brand_Mercedes-Benz     0.078425
age                     0.061805
brand_Lexus             0.041478
brand_Suzuki            0.035750
fuel_Dầu                0.032820
brand_Porsche           0.026399
km                      0.019998
body_group_Hatchback    0.016906
brand_Land Rover        0.014821
brand_Mg                0.013930
body_group_Sedan        0.011098
brand_Toyota            0.010653
brand_Peugeot           0.006730
brand_Other             0.005330
is_imported_False       0.005053
brand_group_Toyota      0.004151
brand_Daewoo            0.004034
dtype: float64

In [40]:
print(importance.tail(20))

body_Kiểu Dáng Khác          0.0
body_Convertible             0.0
body_Minibus                 0.0
body_Mui Trần                0.0
body_Van                     0.0
body_Truck                   0.0
body_Sport Car               0.0
body_Wagon                   0.0
brand_Audi                   0.0
fuel_Điện                    0.0
gearbox_Số sàn               0.0
brand_Honda                  0.0
brand_Volkswagen             0.0
brand_Subaru                 0.0
brand_Mini                   0.0
age_group_Old                0.0
brand_group_Honda            0.0
brand_group_Mercedes-Benz    0.0
brand_group_Vinfast          0.0
imported_age_False_Mid       0.0
dtype: float64

In [46]:
count = (importance.round(2) > 0).sum()
print(count)

18

In [49]:
print(importance[importance.round(2) > 0])

log_age                 0.362697
gearbox_Số tự động      0.130525
brand_group_Other       0.083621
brand_Mercedes-Benz     0.078425
age                     0.061805
brand_Lexus             0.041478
brand_Suzuki            0.035750
fuel_Dầu                0.032820
brand_Porsche           0.026399
km                      0.019998
body_group_Hatchback    0.016906
brand_Land Rover        0.014821
brand_Mg                0.013930
body_group_Sedan        0.011098
brand_Toyota            0.010653
brand_Peugeot           0.006730
brand_Other             0.005330
is_imported_False       0.005053
dtype: float64